/**
 * Style Dictionary 配置文件
 * Mira Design Token
 *
 * 使用方式：
 *   npm install -D style-dictionary
 *   node sd.config.js
 *
 * 输出产物：
 *   dist/tokens.light.css   —— Light 主题 CSS 变量
 *   dist/tokens.dark.css    —— Dark 主题 CSS 变量
 *   dist/tokens.js          —— JS/TS 项目使用的 ESM 对象
 *   dist/tokens.d.ts        —— TypeScript 类型声明
 */

const StyleDictionary = require('style-dictionary');

// ─────────────────────────────────────────────
// 自定义 Transform：数字加 px 单位（dimension 类型）
// ─────────────────────────────────────────────
StyleDictionary.registerTransform({
  name: 'size/px',
  type: 'value',
  matcher: (token) =>
    ['dimension', 'number'].includes(token.$type || token.type) &&
    typeof token.value === 'number' &&
    // spacing / radius / text / blur / shadow offset 等需要 px
    !['opacity', 'font-weight', 'breakpoint', 'container', 'line-height'].some(
      (cat) => token.path.join('.').includes(cat)
    ),
  transformer: (token) => `${token.value}px`,
});

// ─────────────────────────────────────────────
// 自定义 Transform：把拆散的 shadow token 合并成 CSS box-shadow 字符串
// ─────────────────────────────────────────────
StyleDictionary.registerTransform({
  name: 'shadow/css',
  type: 'value',
  matcher: (token) => token.path.includes('shadow') && token.path.includes('color'),
  transformer: () => null, // shadow 子属性不单独输出，由 Format 负责合并
});

// ─────────────────────────────────────────────
// 自定义 Format：生成 CSS 变量文件
// ─────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'css/mira-variables',
  formatter: ({ dictionary, options }) => {
    const selector = options.selector || ':root';
    const tokens = dictionary.allTokens;

    // 把 shadow token 子属性归组
    const shadowGroups = {};
    const regularTokens = [];

    tokens.forEach((token) => {
      const pathStr = token.path.join('.');
      // 匹配 shadow / inset-shadow / drop-shadow 下的子属性
      const shadowMatch = pathStr.match(
        /^((?:Theme\/(?:Light|Dark)\.)?(?:shadow|inset-shadow|drop-shadow)\..+?)\.(color|offset-x|offset-y|blur-radius|spread-radius)$/
      );
      if (shadowMatch) {
        const groupKey = shadowMatch[1];
        if (!shadowGroups[groupKey]) shadowGroups[groupKey] = {};
        shadowGroups[groupKey][shadowMatch[2]] = token.value;
        shadowGroups[groupKey].__path = token.path.slice(0, -1); // 去掉最后一级
      } else {
        regularTokens.push(token);
      }
    });

    const lines = [`${selector} {`];

    // 普通 token
    regularTokens.forEach((token) => {
      // 跳过 shadow 子属性（已归组处理）
      const last = token.path[token.path.length - 1];
      if (['offset-x', 'offset-y', 'blur-radius', 'spread-radius'].includes(last)) return;

      const varName = '--' + token.path
        .join('-')
        .replace(/\//g, '-')       // Theme/Light -> Theme-Light
        .replace(/\s+/g, '-')      // tailwind colors -> tailwind-colors
        .replace(/[^a-zA-Z0-9-_]/g, '-')
        .toLowerCase();

      let value = token.value;
      if (typeof value === 'number') {
        // 判断是否需要 px
        const needsPx = ['font-size', 'line-height', 'radius', 'blur', 'spacing',
          'width', 'height', 'border-width', 'offset', 'shadow']
          .some((k) => token.path.join('.').includes(k));
        value = needsPx ? `${value}px` : value;
      }

      lines.push(`  ${varName}: ${value};`);
    });

    // 合并 shadow token
    Object.entries(shadowGroups).forEach(([, parts]) => {
      if (!parts.__path) return;
      const varName = '--' + parts.__path
        .join('-')
        .replace(/\//g, '-')
        .replace(/\s+/g, '-')
        .replace(/[^a-zA-Z0-9-_]/g, '-')
        .toLowerCase();

      const isInset = parts.__path.includes('inset-shadow');
      const shadow = [
        isInset ? 'inset' : '',
        `${parts['offset-x'] ?? 0}px`,
        `${parts['offset-y'] ?? 0}px`,
        `${parts['blur-radius'] ?? 0}px`,
        `${parts['spread-radius'] ?? 0}px`,
        parts['color'] ?? 'transparent',
      ]
        .filter(Boolean)
        .join(' ');

      lines.push(`  ${varName}: ${shadow};`);
    });

    lines.push('}');
    return lines.join('\n') + '\n';
  },
});

// ─────────────────────────────────────────────
// 自定义 Format：生成 ESM JS 对象
// ─────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'js/esm-object',
  formatter: ({ dictionary }) => {
    const obj = {};
    dictionary.allTokens.forEach((token) => {
      // 用路径构建嵌套对象
      let cursor = obj;
      token.path.forEach((seg, i) => {
        if (i === token.path.length - 1) {
          cursor[seg] = token.value;
        } else {
          cursor[seg] = cursor[seg] || {};
          cursor = cursor[seg];
        }
      });
    });
    return `// Auto-generated by Style Dictionary — do not edit manually\nexport const tokens = ${JSON.stringify(obj, null, 2)};\nexport default tokens;\n`;
  },
});

// ─────────────────────────────────────────────
// Token 文件分组（基础色 + Tailwind + 语义色）
// ─────────────────────────────────────────────
const BASE_FILES = ['tokens-fixed.json']; // 单文件包含所有 token set

// ─────────────────────────────────────────────
// Light 主题配置
// ─────────────────────────────────────────────
const lightConfig = {
  source: BASE_FILES,
  platforms: {
    css: {
      transformGroup: 'css',
      transforms: ['size/px'],
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.light.css',
          format: 'css/mira-variables',
          filter: (token) =>
            token.filePath === BASE_FILES[0] &&
            token.path[0] === 'Theme/Light',
          options: {
            selector: ':root, [data-theme="light"]',
          },
        },
      ],
    },
  },
};

// ─────────────────────────────────────────────
// Dark 主题配置
// ─────────────────────────────────────────────
const darkConfig = {
  source: BASE_FILES,
  platforms: {
    css: {
      transformGroup: 'css',
      transforms: ['size/px'],
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.dark.css',
          format: 'css/mira-variables',
          filter: (token) =>
            token.filePath === BASE_FILES[0] &&
            token.path[0] === 'Theme/Dark',
          options: {
            selector: '[data-theme="dark"], .dark',
          },
        },
      ],
    },
  },
};

// ─────────────────────────────────────────────
// 基础 Token（Tailwind 色板 + 通用 Token）
// ─────────────────────────────────────────────
const baseConfig = {
  source: BASE_FILES,
  platforms: {
    css: {
      transformGroup: 'css',
      transforms: ['size/px'],
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.base.css',
          format: 'css/mira-variables',
          filter: (token) =>
            token.filePath === BASE_FILES[0] &&
            token.path[0] === 'TailwindCSS/Default',
          options: { selector: ':root' },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.js',
          format: 'js/esm-object',
        },
      ],
    },
  },
};

// ─────────────────────────────────────────────
// 执行构建
// ─────────────────────────────────────────────
[lightConfig, darkConfig, baseConfig].forEach((cfg) => {
  const sd = StyleDictionary.extend(cfg);
  sd.buildAllPlatforms();
});

console.log('\n✅ Style Dictionary build complete!');
console.log('   dist/tokens.base.css   —— Tailwind 基础色板变量');
console.log('   dist/tokens.light.css  —— Light 主题语义变量');
console.log('   dist/tokens.dark.css   —— Dark 主题语义变量');
console.log('   dist/tokens.js         —— JS/TS ESM 对象');
